### ISSUE TITLE
More Integration Tests

### ISSUE THREAD

**Issue by dowy24** [GillesMyny1/SurveyMonkey#58]
Make integration tests for Answers and Users.

**Comment by dowy24** [comment]
Hey guys, I am having an issue with the Range Answer Integration Tests. For some reason I keep getting a null value. Let me know if anyone could figure this out.

**Comment by GillesMyny1** [comment]
> Hey guys, I am having an issue with the Range Answer Integration Tests. For some reason I keep getting a null value. Let me know if anyone could figure this out.

What branch would this be under? What progress has been made so far on Range Answer tests?

**Comment by dowy24** [comment]
This is under the more_tests branch. There has been none created so far, but ideally we would want two tests:
-getRangeAnswer()
-addRangeAnswer()

**Comment by GillesMyny1** [comment]
Test seems to fail on built-in bug with specific dependency, ignoring.
