### ISSUE TITLE
ChoiceQna - List<String> - 'Basic' attribute type should not be a container

### ISSUE THREAD

**Issue by GillesMyny1** [GillesMyny1/SurveyMonkey#7]
Need help with this error, not sure what it's mad about.

![image](https://user-images.githubusercontent.com/91336156/222596293-a403fa22-adab-4c0a-b7e8-7d37ac73290d.png)

**Comment by dowy24** [comment]
Resolved adca54f57dae6f83612cccb2f64648f71c95e6bb
